baseURL = "https://bazengirungu.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Duncan Maina"
theme = "blowfish"


enableRobotsTXT = true
[pagination]
  pagerSize = 10
summaryLength = 30

buildDrafts = false
buildFuture = false

googleAnalytics = "YOUR_GA_ID" # Optional

[imaging]
  anchor = 'Center'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 95
  resampleFilter = 'Box'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]