languageCode = "en"
languageName = "English"
weight = 1
title = "Big Dawgs Eat"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Duncan Maina"
  email = "duncancybershujaa@gmail.com"
  image = "img/blowfish_logo.png"
  headline = "Trainer | Digital Forensics | SOC Operations | Threat Intelligence"
  bio = "Cybersecurity trainer and blue-team practitioner focused on digital forensics, threat hunting and SOC Operations."
  links = [
    { x-twitter = "https://twitter.com/bazengirungu" },
    { github = "https://github.com/bazengirungu" },
    { email = "mailto:duncanirungu@proton.me" },
    { discord = "https://discord.gg/2cRdBs8" },
    { linkedin = "https://linkedin.com/in/duncanirungu" }
  ]